[tool.poetry]
name = "mri-digital-twin"
version = "0.1.0"
description = "Agentic Digital Twin of an MRI Scanner"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
langgraph = "*"
numpy = "*"
matplotlib = "*"
